export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const SET_PRODUCT_DETAIL = "SET_PRODUCT_DETAIL";
